name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的历史记录

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Display dotnet version
        run: dotnet --version
          
      - name: Clean
        run: dotnet clean --configuration Release

      - name: Restore dependencies
        run: dotnet restore

      - name: List project files
        run: find . -name "*.csproj" -type f

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o release --nologo

      - name: Verify release directory
        run: ls -la release

      - name: Verify wwwroot directory
        run: |
          if [ -d "release/wwwroot" ]; then
            ls -la release/wwwroot
            echo "Checking important files:"
            find release/wwwroot -type f -not -path "*/\.*" | sort
          else
            echo "wwwroot directory not found!"
            exit 1
          fi

      - name: Copy 404.html to output
        run: |
          if [ -f "release/wwwroot/index.html" ] && [ ! -f "release/wwwroot/404.html" ]; then
            cp release/wwwroot/index.html release/wwwroot/404.html
            echo "Created 404.html from index.html"
          fi

      - name: Create .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Ensure correct base path
        run: |
          if grep -q 'base href="/"' release/wwwroot/index.html; then
            echo "Updating base href in index.html"
            sed -i 's|<base href="/" />|<base href="/grokbot/" />|g' release/wwwroot/index.html
          fi
          
          if [ -f "release/wwwroot/404.html" ]; then
            echo "Updating base href in 404.html"
            sed -i 's|<base href="/" />|<base href="/grokbot/" />|g' release/wwwroot/404.html
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: release/wwwroot
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true  # 清理目标分支
